services:
  db:
    image: postgres:16
    container_name: runner-ai
    environment:
      POSTGRES_USER: runneradmin
      POSTGRES_PASSWORD: runner123
      POSTGRES_DB: runnerai_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
